POST http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvcm1hIiwiaWQiOiI2Mzk3YmQ5NjhjM2M5ZjliMWI2MDA1ZjMiLCJpYXQiOjE2NzA5NzU5MzJ9.mZQIUlGCIIM3oH03FHjk5yzFrg15J-kcetbuOzBfpFU
Content-Type: application/json

{
    "title": "Tämä on vettä",
    "author": "Jorma Penttinen",
    "url": "http://www.blogi.fi/",
    "likes": 1553
}